
swagger: '2.0'

paths:
  "search/pontos":
    $ref: "./search/pontos.yaml"
  "pontos":
    $ref: "./paths/ponto.yaml#/definitions/create"
  "pontos/{id}":
    $ref: "./paths/ponto.yaml#/definitions/byId"

